services:
  php:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app/public
    environment:
        - "SERVER_NAME=:8000"
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql:Z
  adminer:
    image: adminer:latest
    ports:
      - 13306:8080

volumes:
  db:
